language: python

matrix:
    include:
        - os: linux
          python: "3.5"

        - os: linux
          python: "3.6"

        - os: osx
          python: "3.5"

        - os: osx
          python: "3.6"

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi

install: pip install tox-travis

script:
  - tox -e travis

env:
  OMP_NUM_THREADS: 4
