language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install tox-travis

script: tox -e travis

# Macos Testing
matrix:
  include:
    - name: "Python: 3.8"
      os: osx
      osx_image: xcode11.3
      language: sh
      script: tox -e nolinux
    - name: "Python: 3.7"
      os: osx
      osx_image: xcode10.2
      language: sh
      script: tox -e nolinux
    - name: "Python: 3.6"
      os: osx
      osx_image: xcode9.4
      language: sh
      script: tox -e nolinux

env:
  OMP_NUM_THREADS: 4
