language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install: "make install"
# command to run tests
script:
  - "make test"
  - "make checkstyle"
