language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

python:
  - 3.8

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install tox-travis

script: tox -e travis

# Macos Testing
matrix:
  include:
    - name: "MacOS"
      os: osx
      language: sh
      script: tox -e nolinux
    - name: "Windows"
      os: windows
      language: sh
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install: choco install python
      install:
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
        - pip install Cython --install-option="--no-cython-compile"
        - python setup.py develop
      script: py.test -m "not nolinux"

env:
  OMP_NUM_THREADS: 4
